### ISSUE TITLE
Dynamic Modules: Identifier field header in grid view cannot be changed by editing the label property

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#213] opened 2020-08-20 15:28 UTC
In the grid view where we visualize the content item list for a specific content type, we would like to edit the header name for every column (Image: GridView.png). We found out that we can do this by changing the "Label" property of the field that we want to display in the grid but this is not working for the field that is set as Identifier (Image: LabelProperty.png). 

We change the label to "Long Item Number" but in the grid this change is not being applied and instead is displaying the name of the field "LongItemNumber".

Could this be adjusted so it works properly for the field set as Identifier?

Thanks.

![LabelProperty](https://user-images.githubusercontent.com/69977848/90791809-e9ac3300-e2c6-11ea-8173-7ca7912d4b73.png)

![GridView](https://user-images.githubusercontent.com/69977848/90791583-9c2fc600-e2c6-11ea-8d14-f70e82cdec28.png)

**Comment by mstratiev** [comment] 2020-09-29 11:04
Could you please provide more information about the version of Sitefinity that you are using, since with our latest release I cannot seem to reproduce it and setting a different label with spaces is properly applied.
![image](https://user-images.githubusercontent.com/13236125/94550597-a8f7f000-025c-11eb-8246-66fa12ead47d.png)

**Comment by dehivis24** [comment] 2020-09-29 14:45
We are currently working on Sitefinity 13.1.7400. 
It works for all columns except for the Identifier field column. For example we are using an identifier field different than Title, in our case "LongItemNumber" and we want to display it in the grid with spaces (Long Item Number) just like in the picture that I posted and it doesn´t work.

**Comment by mstratiev** [comment] 2020-09-29 15:24
Alright, I double-checked it with the identifier field. And it takes the developer name rather than the given label.

I would suggest opening a support case so that our support engineers would be able to either give you more details or resources or log a bug if it is needed.

**Comment by Novkirishki** [comment] 2020-10-27 08:33
This issue should be now fixed with Sitefinity 13.1.7424

**Closed by Novkirishki** 2020-10-27 08:33 UTC
Labels: bug, triaged
